### ISSUE TITLE
Failed load

### ISSUE THREAD

**Issue by szogun1910** [Stimayk/ServersInfo#1]
css:247 
mm: 2.0.0-dev+1290
```
2024-07-16 21:52:31.967 +02:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/data/xxx/xxx/xxx/addons/counterstrikesharp/plugins/ServersInfo/ServersInfo.dll
System.Collections.Generic.KeyNotFoundException: The given key 'menu:nfcore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CounterStrikeSharp.API.Core.Capabilities.PluginCapability`1.Get() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Capabilities/PluginCapability.cs:line 17
   at ServersInfo.ServersInfo.Load(Boolean hotReload) in C:\Users\Stimayk\Documents\GitHub\WpPluginSources\ServersInfo\ServersInfo.cs:line 37
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
```

**Comment by ZeroCPU** [comment]
me too

**Comment by Stimayk** [comment]
Fix in next upd
